"""add org_id to sites and conversations, invite_code and contract dates

Revision ID: d7a4d75a3d5f
Revises: 
Create Date: 2026-04-20 15:05:53.591102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a4d75a3d5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('organization_id', sa.UUID(), nullable=True, comment='소속 조직 ID (같은 조직 멤버만 참여 가능)'))
    op.create_foreign_key(None, 'conversations', 'organizations', ['organization_id'], ['id'])
    op.add_column('organization_members', sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='입사/계약 시작일'))
    op.add_column('organization_members', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True, comment='퇴사/계약 만료일 (null=재직 중, 과거 날짜=접근 차단)'))
    # invite_code: nullable로 먼저 추가 → 기존 행 채우기 → NOT NULL 전환
    op.add_column('organizations', sa.Column('invite_code', sa.String(length=8), nullable=True, comment='8자리 초대 코드 (조직 가입용)'))
    # 기존 조직에 랜덤 코드 부여
    conn = op.get_bind()
    orgs = conn.execute(sa.text("SELECT id FROM organizations WHERE invite_code IS NULL")).fetchall()
    alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
    import secrets
    for org in orgs:
        code = "".join(secrets.choice(alphabet) for _ in range(8))
        conn.execute(sa.text("UPDATE organizations SET invite_code = :code WHERE id = :id"), {"code": code, "id": org[0]})
    op.alter_column('organizations', 'invite_code', nullable=False)
    op.create_index('idx_org_invite_code', 'organizations', ['invite_code'], unique=False)
    op.create_unique_constraint(None, 'organizations', ['invite_code'])
    op.add_column('sites', sa.Column('organization_id', sa.UUID(), nullable=True, comment='소속 조직 ID (멀티테넌트 격리 기준)'))
    op.create_index('idx_sites_org_id', 'sites', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sites_organization_id'), 'sites', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'sites', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.drop_index(op.f('ix_sites_organization_id'), table_name='sites')
    op.drop_index('idx_sites_org_id', table_name='sites')
    op.drop_column('sites', 'organization_id')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_index('idx_org_invite_code', table_name='organizations')
    op.drop_column('organizations', 'invite_code')
    op.drop_column('organization_members', 'ended_at')
    op.drop_column('organization_members', 'started_at')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'organization_id')
    # ### end Alembic commands ###
